### ISSUE TITLE
WiSci Arduino code is no longer available? why?

### ISSUE THREAD

**Issue by ghost** [AkshatWahi/AL_PIC#1]
@AkshatWahi @ishankothari @arjunpola
the code for WiSci is no longer available at github.com/AkshatWahi/WiSci_Arduino_code
Can you re-upload the code.

Also, I want to buy a WiSci , can you reply back so that we can discuss the quantity and shipping.
waiting for your reply

**Comment by mylkes** [comment]
> @AkshatWahi @ishankothari @arjunpola
> the code for WiSci is no longer available at github.com/AkshatWahi/WiSci_Arduino_code
> Can you re-upload the code.
> 
> Also, I want to buy a WiSci , can you reply back so that we can discuss the quantity and shipping.
> waiting for your reply

You can try putting the URL into the Wayback Machine
